### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by ghost** [TechnitiumSoftware/DNS-over-HTTPS#1]
The service does not seem to be working with all DoH utilities. I've installed the service on a Windows Server running IIS. 

I can query the service using dig, but other tools like curl, dog do not work. Dog for example reports:
Error [protocol]: Malformed packet: insufficient data

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will check the issue soon. 

If you are looking to run DoH service then it is recommended to use Technitium DNS Server for it. The DNS-over-HTTPS project is intended to be used for providing DoH protocol support for DNS servers that do not yet support it.

**Comment by ghost** [comment]
That is basically the use case I am using it for - as a proxy for another DNS service.

**Comment by ShreyasZare** [comment]
> That is basically the use case I am using it for - as a proxy for another DNS service.

Please share the curl command that you are trying to test it and also the output you see.

**Comment by ShreyasZare** [comment]
I have updated the implementation that fixes some known issues and now works the same way DoH is handled in the Technitium DNS Server project.

Do update to the latest code and check if its working well. Let me know your feedback here.
